abrevs = {
          "Atlanta Hawks": 'ATL',
          "Baltimore Bullets": 'BAL',
          "Boston Celtics": 'BOS',
          "Brooklyn Nets": 'BRK',
          "Buffalo Braves": 'BUF',
          "Carolina Cougars": 'CAR',
          "Charlotte Hornets": 'CHO',
          "Charlotte Bobcats": 'CHA',
          "Chicago Bulls": 'CHI',
          "Cleveland Cavaliers": 'CLE',
          "Dallas Chaparrals": 'DLC',
          "Dallas Mavericks": 'DAL',
          "Detroit Pistons": 'DET',
          "Denver Nuggets": {
              'ABA': 'DNR',
              'NBA': 'DEN'
          },
          "Denver Rockets": 'DNR',
          "Golden State Warriors": 'GSW',
          "Houston Rockets": 'HOU',
          "Indiana Pacers": {
              'ABA': 'INA',
              'NBA': 'IND'
          },
          "Kansas City Kings": 'KCK',
          "Kansas City-Omaha Kings": 'KCO',
          "Kentucky Colonels": 'KEN',
          "Los Angeles Lakers": 'LAL',
          "Los Angeles Clippers": 'LAC',
          "Miami Heat": 'MIA',
          "Milwaukee Bucks": 'MIL',
          "Minnesota Timberwolves": 'MIN',
          "Memphis Tams": 'MMT',
          "Memphis Sounds": "MMS",
          "Memphis Grizzlies": 'MEM',
          "New Orleans Jazz": "NOJ",
          "New Orleans Hornets": "NOH",
          "New Orleans Pelicans": "NOP",
          "New Orleans/Oklahoma City Hornets": "NOK",
          "New York Knicks": "NYK",
          "New York Nets": {
              'ABA': 'NYA',
              'NBA': 'NYN'
          },
          "New Jersey Nets": 'NJN',
          "Orlando Magic": 'ORL',
          "Oklahoma City Thunder": 'OKC',
          "Philadelphia 76ers": 'PHI',
          "Phoenix Suns": 'PHO',
          "Portland Trail Blazers": 'POR',
          "Sacramento Kings": 'SAC',
          "San Antonio Spurs": 'SAS',
          "San Diego Conquistadors": 'SDA',
          "Seattle SuperSonics": 'SEA',
          "Toronto Raptors": 'TOR',
          "Utah Jazz": 'UTA',
          "Utah Stars": 'UTS',
          "Vancouver Grizzlies": 'VAN',
          "Virginia Squires": 'VIR',
          "Washington Bullets": 'WSB',
          "Washington Wizards": 'WAS'
}